# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-24 04:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='name', max_length=50, null=True, verbose_name='型号/品牌（中文名）')),
                ('first_letter', models.CharField(blank=True, max_length=1, null=True, verbose_name='首字母')),
                ('slug_global', models.CharField(blank=True, max_length=32, null=True)),
                ('slug', models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='型号/品牌（英文简写）')),
                ('mum', models.CharField(blank=True, max_length=32, null=True, verbose_name='厂商')),
                ('classified', models.CharField(blank=True, choices=[('微型车', '微型车'), ('小型车', '小型车'), ('紧凑型车', '紧凑型车'), ('中型车', '中型车'), ('中大型车', '中大型车'), ('豪华型车', '豪华型车'), ('小型SUV', '小型SUV'), ('紧凑型SUV', '紧凑型SUV'), ('中型SUV', '中型SUV'), ('中大型SUV', '中大型SUV'), ('全尺寸SUV', '全尺寸SUV'), ('MPV', 'MPV'), ('跑车', '跑车'), ('微面', '微面'), ('微卡', '微卡'), ('轻客', '轻客'), ('皮卡', '皮卡')], max_length=32, null=True, verbose_name='级别')),
                ('keywords', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('logo_img', models.CharField(blank=True, max_length=200, null=True)),
                ('thumbnail', models.CharField(blank=True, max_length=200, null=True, verbose_name='缩略图')),
                ('pinyin', models.CharField(blank=True, db_index=True, max_length=32, null=True, verbose_name='型号/品牌（拼音）')),
                ('status', models.CharField(blank=True, choices=[('A', 'ADD 刚添加的品牌或型号'), ('Y', 'YES 确定投入使用的品牌或型号'), ('D', 'DELETE 标记为需要删除的品牌或型号')], default='A', max_length=1, null=True)),
                ('attribute', models.CharField(blank=True, choices=[('合资', '合资'), ('进口', '进口'), ('国产', '国产')], db_index=True, max_length=10, null=True, verbose_name='属性，区分国产还是进口等')),
                ('units', models.IntegerField(default=0, verbose_name='参与统计的该型号车源数量')),
                ('popular', models.CharField(blank=True, choices=[('A', '畅销'), ('B', '一般'), ('C', '冷门')], default='B', max_length=1, null=True)),
                ('score', models.IntegerField(default=0, verbose_name='百度搜索指数')),
                ('alias', models.CharField(blank=True, max_length=50, null=True, verbose_name='别名')),
                ('brand_area', models.CharField(blank=True, max_length=20, null=True, verbose_name='产地')),
                ('parent', models.ForeignKey(blank=True, db_column='parent', db_constraint=False, max_length=32, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='models', to='category.Category', to_field='slug', verbose_name='品牌（英文简写）')),
            ],
            options={
                'db_table': 'open_category',
            },
        ),
        migrations.CreateModel(
            name='ModelDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_model', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('detail_model_slug', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('price_bn', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('url', models.URLField(blank=True, db_index=True, default='', null=True)),
                ('year', models.IntegerField(blank=True, default=0, verbose_name='年款')),
                ('volume', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='排量')),
                ('domain', models.CharField(blank=True, max_length=32, null=True)),
                ('status', models.CharField(blank=True, choices=[('A', 'ADD 刚添加的款型'), ('Y', 'YES 确定可投入使用的款型'), ('D', 'DELETE 标记为需要删除的款型')], default='A', max_length=1, null=True)),
                ('has_param', models.CharField(blank=True, choices=[('Y', 'YES 有配置参数信息'), ('N', 'NO 无配置参数信息')], default='N', max_length=1, null=True)),
                ('listed_year', models.IntegerField(blank=True, default=0, verbose_name='上市年份')),
                ('delisted_year', models.IntegerField(blank=True, null=True, verbose_name='退市年份')),
                ('control', models.CharField(blank=True, db_index=True, max_length=32, null=True, verbose_name='变速箱')),
                ('emission_standard', models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='排放标准')),
                ('continuity_id', models.IntegerField(blank=True, null=True, verbose_name='款型系列id')),
                ('vv', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='虚拟排量')),
                ('global_slug', models.ForeignKey(blank=True, db_column='global_slug', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_detail', to='category.Category', to_field='slug')),
            ],
            options={
                'db_table': 'open_model_detail',
            },
        ),
    ]
