version: "3"
services:
  evalapi_bee:
    image: "evalapi_bee:latest"
    ports:
      - "80:80"
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 600M
      update_config:
        parallelism: 1
        delay: 1s
      restart_policy:
        condition: any
        max_attempts: 3
        delay: 1s
      placement:
        constraints: [node.role == manager]