# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-24 02:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('slug', models.CharField(blank=True, db_index=True, max_length=32, null=True)),
                ('pinyin', models.CharField(blank=True, db_index=True, max_length=32, null=True)),
                ('quhao', models.CharField(blank=True, db_index=True, max_length=32, null=True)),
                ('url', models.URLField()),
                ('priority', models.IntegerField(null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('area', models.CharField(max_length=5, verbose_name='区域')),
                ('city_administration_number', models.IntegerField(null=True, verbose_name='城市行政区号')),
                ('parentid', models.ForeignKey(db_column='parentid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='general.City', verbose_name='parent use id')),
            ],
            options={
                'db_table': 'open_city',
            },
        ),
    ]
