# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-24 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarDealHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_zh', models.CharField(blank=True, max_length=32, null=True, verbose_name='品牌名称')),
                ('model_zh', models.CharField(blank=True, max_length=32, null=True, verbose_name='型号名称')),
                ('model_detail_zh', models.CharField(blank=True, max_length=50, null=True, verbose_name='款型名称')),
                ('brand_slug', models.CharField(blank=True, db_index=True, max_length=32, null=True, verbose_name='品牌slug')),
                ('model_slug', models.CharField(blank=True, db_index=True, max_length=32, null=True, verbose_name='型号slug')),
                ('model_detail_slug', models.CharField(blank=True, db_index=True, max_length=32, null=True, verbose_name='款型slug')),
                ('year', models.IntegerField(blank=True, db_index=True, default=0, verbose_name='初次上牌年份')),
                ('month', models.IntegerField(blank=True, default=6, verbose_name='初次上牌月份')),
                ('mile', models.DecimalField(blank=True, decimal_places=2, help_text='单位万公里', max_digits=5, null=True, verbose_name='行驶里程')),
                ('volume', models.DecimalField(blank=True, db_index=True, decimal_places=1, max_digits=5, null=True, verbose_name='排量')),
                ('color', models.CharField(blank=True, max_length=32, null=True, verbose_name='颜色')),
                ('control', models.CharField(blank=True, max_length=32, null=True, verbose_name='变速箱')),
                ('province', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='省份')),
                ('city', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='城市')),
                ('deal_time', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='成交时间')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='成交价格')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('deal_type', models.CharField(blank=True, choices=[('sell_dealer', '商家收购'), ('trade_in', '置换'), ('auction', '拍卖'), ('private_party', '个人交易'), ('buy_dealer', '商家零售'), ('buy_cpo', '认证二手车')], max_length=20, null=True, verbose_name='交易方式')),
                ('source', models.CharField(blank=True, max_length=50, null=True, verbose_name='历史成交数据来源')),
            ],
            options={
                'verbose_name': '二手车成交历史数据',
                'db_table': 'car_deal_history',
            },
        ),
        migrations.CreateModel(
            name='CarDealHistoryStatatics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_slug', models.CharField(max_length=32, null=True, verbose_name='型号')),
                ('city', models.CharField(max_length=50, null=True, verbose_name='城市')),
                ('date', models.DateField(null=True, verbose_name='日期')),
                ('count', models.IntegerField(null=True, verbose_name='数量')),
            ],
            options={
                'db_table': 'car_deal_history_statatics',
            },
        ),
    ]
